
CREATE TABLE CLIENTS
(
ID INT PRIMARY KEY IDENTITY,
NAME VARCHAR(60) NOT NULL,
CPF CHAR(11) NOT NULL,
RG VARCHAR(9) NOT NULL,  
PHONE1 VARCHAR(11) NOT NULL,
PHONE2 VARCHAR(11) NULL,
EMAIL VARCHAR(100) NOT NULL,
CONSTRAINT UQ_CLIENTS_CPF UNIQUE (CPF),
CONSTRAINT UQ_CLIENTS_RG UNIQUE (RG),
CONSTRAINT UQ_CLIENTS_EMAIL UNIQUE (EMAIL)
)

CREATE TABLE EMPLOYEES
(
ID INT PRIMARY KEY IDENTITY,
NAME VARCHAR(60) NOT NULL,
CPF CHAR(11) NOT NULL,
RG VARCHAR(9) NOT NULL,
PHONE VARCHAR(11) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
SENHA VARCHAR(100) NOT NULL,
CONSTRAINT UQ_EMPLOYEES_CPF UNIQUE (CPF),
CONSTRAINT UQ_EMPLOYEES_RG UNIQUE (RG),
CONSTRAINT UQ_CLIENTS_EMAIL UNIQUE (EMAIL),
ISADM BIT NOT NULL
)

CREATE TABLE ADDRESSES
(
ID INT PRIMARY KEY IDENTITY,
STREET VARCHAR(100) NOT NULL,
NUMBER VARCHAR(10) NOT NULL,
DISTRICT VARCHAR(20) NOT NULL,
CEP CHAR(8) NOT NULL,
EMPLOYEEID INT NOT NULL,
CONSTRAINT FK_ADDRESS_EMPLOYEES FOREIGN KEY (EMPLOYEEID)
REFERENCES EMPLOYEES
)

CREATE TABLE SUPPLIERS
(
ID INT PRIMARY KEY IDENTITY,
COMPANYNAME VARCHAR(70) NOT NULL,
CNPJ CHAR(14) NOT NULL UNIQUE,
CONTRACTNAME VARCHAR(70) NOT NULL,
PHONE VARCHAR(11) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
CONSTRAINT UQ_CLIENTS_EMAIL UNIQUE (EMAIL),
)

CREATE TABLE PRODUCTS
(
ID INT PRIMARY KEY IDENTITY,
NAME VARCHAR(70) NOT NULL,
DESCRIPTION VARCHAR(70) NOT NULL,
PRICE FLOAT NOT NULL,
QUANTITY INT NOT NULL,
SUPPLIERID INT NOT NULL,
CONSTRAINT FK_PRODUCTS_SUPPLIER FOREIGN KEY (SUPPLIERID)
REFERENCES SUPPLIERS,
UNIQUE(NAME, DESCRIPTION)
)

CREATE TABLE INCOMES
(
ID INT PRIMARY KEY IDENTITY,
SUPPLIERID INT NOT NULL,
CONSTRAINT FK_INCOMES_SUPPLIER FOREIGN KEY (SUPPLIERID)
REFERENCES SUPPLIERS,
ENTRYDATE DATETIME NOT NULL DEFAULT GETDATE(),
EMPLOYEEID INT NOT NULL,
TOTALVALUE FLOAT NOT NULL,
CONSTRAINT FK_INCOMES_EMPLOYEES FOREIGN KEY (EMPLOYEEID)
REFERENCES EMPLOYEES
)

CREATE TABLE INCOMEITEMS
(
INCOMEID INT NOT NULL
CONSTRAINT FK_INCOMEITEMS_INCOMES FOREIGN KEY (INCOMEID)
REFERENCES PRODUCTSINCOME,
PRODUCTID INT NOT NULL
CONSTRAINT FK_INCOMEITEMS_PRODUCTS FOREIGN KEY (PRODUCTID)
REFERENCES PRODUCTS,
QUANTITY INT NOT NULL,
UNITYPRICE FLOAT NOT NULL,
PRIMARY KEY (INCOMEID, PRODUCTID)
)


CREATE TABLE SALES
(
ID INT PRIMARY KEY IDENTITY,
CLIENTID INT NOT NULL,
CONSTRAINT FK_SALES_CLIENTS FOREIGN KEY (CLIENTID)
REFERENCES CLIENTS,
SALEDATE DATETIME NOT NULL DEFAULT GETDATE(),
EMPLOYEEID INT NOT NULL,
TOTALVALUE FLOAT NOT NULL
CONSTRAINT FK_PRODUCTSINCOME_EMPLOYEE FOREIGN KEY (EMPLOYEEID)
REFERENCES EMPLOYEES
)

CREATE TABLE SALEITEMS
(
SALEID INT NOT NULL
CONSTRAINT FK_SALEITEMS_PRODUCTSINCOME FOREIGN KEY (SALEID)
REFERENCES SALES,
PRODUCTID INT NOT NULL
CONSTRAINT FK_SALES_PRODUCTS FOREIGN KEY (PRODUCTID)
REFERENCES PRODUCTS,
QUANTITY INT NOT NULL,
UNITYPRICE FLOAT NOT NULL,
PRIMARY KEY (SALEID, PRODUCTID)
)


CREATE TABLE ROOMS
(
ID INT PRIMARY KEY IDENTITY,
NUMBER VARCHAR(10) NOT NULL,
ROOMFLOOR VARCHAR(10) NOT NULL,
ROOMTYPE INT NOT NULL,
PRICEPERDAY FLOAT NOT NULL,
)

CREATE TABLE RESERVATIONS
(
ID INT PRIMARY KEY IDENTITY,
CLIENTID INT NOT NULL,
CONSTRAINT FK_RESERVATIOS_CLIENTS FOREIGN KEY (CLIENTID)
REFERENCES CLIENTS,
ROOMID INT NOT NULL,
CONSTRAINT FK_RESERVATIONS_ROOMS FOREIGN KEY (ROOMID)
REFERENCES ROOMS,
CHECKIN DATETIME NOT NULL,
CHECKOUT DATETIME NOT NULL,
NUMBEROFADULTS INT NOT NULL,
NUMBEROFKIDS INT NOT NULL,
)

CREATE TABLE CHECKINS
(
ID INT PRIMARY KEY IDENTITY,
RESERVATIONID INT NULL,
CONSTRAINT FK_CHECKINS_RESERVATIONS FOREIGN KEY (RESERVATIONID)
REFERENCES RESERVATIONS,
ROOMID INT NOT NULL,
CONSTRAINT FK_CHECKINS_ROOMS FOREIGN KEY (ROOMID)
REFERENCES ROOMS,
)

CREATE TABLE CHECKOUTS
(
CHECKINID INT NOT NULL,
CONSTRAINT FK_CHECKOUTS_CHECKINS FOREIGN KEY (CHECKINID)
REFERENCES CHECKINS,
TOTALVALUE FLOAT NOT NULL
)



