CREATE TABLE [dbo].[CLIENTS] (
    [ID]     INT           IDENTITY (1, 1) NOT NULL,
    [NAME]   VARCHAR (60)  NOT NULL,
    [CPF]    CHAR (11)     NOT NULL,
    [RG]     VARCHAR (9)   NOT NULL,
    [PHONE1] VARCHAR (11)  NOT NULL,
    [PHONE2] VARCHAR (11)  NULL,
    [EMAIL]  VARCHAR (100) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UQ_CLIENTS_EMAIL] UNIQUE NONCLUSTERED ([EMAIL] ASC),
    CONSTRAINT [UQ_CLIENTS_RG] UNIQUE NONCLUSTERED ([RG] ASC),
    CONSTRAINT [UQ_CLIENTS_CPF] UNIQUE NONCLUSTERED ([CPF] ASC)
);
CREATE TABLE [dbo].[EMPLOYEES] (
    [ID]           INT           IDENTITY (1, 1) NOT NULL,
    [NAME]         VARCHAR (60)  NOT NULL,
    [CPF]          CHAR (11)     NOT NULL,
    [RG]           VARCHAR (15)  NOT NULL,
    [PHONE]        VARCHAR (11)  NOT NULL,
    [EMAIL]        VARCHAR (100) NOT NULL,
    [PASSWORD]     VARCHAR (20)  NOT NULL,
    [STREET]       VARCHAR (60)  NOT NULL,
    [NUMBER]       VARCHAR (10)  NOT NULL,
    [DISTRICT]     VARCHAR (30)  NOT NULL,
    [CEP]          VARCHAR (9)   NOT NULL,
    [EMPLOYEETYPE] INT           NOT NULL,
    [CITY]         VARCHAR (50)  NOT NULL,
    [ACTIVE]       BIT           NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UQ_EMPLOYEES_CPF] UNIQUE NONCLUSTERED ([CPF] ASC),
    CONSTRAINT [UQ_EMPLOYEES_RG] UNIQUE NONCLUSTERED ([RG] ASC),
    CONSTRAINT [UQ_EMPLOYEES_EMAIL] UNIQUE NONCLUSTERED ([EMAIL] ASC)
);
CREATE TABLE [dbo].[PRODUCTS] (
    [ID]          INT           IDENTITY (1, 1) NOT NULL,
    [NAME]        VARCHAR (70)  NOT NULL,
    [DESCRIPTION] VARCHAR (100) NOT NULL,
    [PRICE]       FLOAT (53)    DEFAULT ((0.00)) NOT NULL,
    [STOCK]       INT           DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);
CREATE TABLE [dbo].[ROOMS] (
    [ID]               INT          IDENTITY (1, 1) NOT NULL,
    [NUMBER]           VARCHAR (10) NOT NULL,
    [ROOMFLOOR]        INT          NOT NULL,
    [ROOMTYPE]         INT          NOT NULL,
    [PRICEPERDAY]      FLOAT (53)   NOT NULL,
    [ROOMAVAILABILITY] BIT          NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UQ_ROOMS_NUMBER] UNIQUE NONCLUSTERED ([NUMBER] ASC)
);
CREATE TABLE [dbo].[SUPPLIERS] (
    [ID]          INT           IDENTITY (1, 1) NOT NULL,
    [COMPANYNAME] VARCHAR (70)  NOT NULL,
    [CNPJ]        CHAR (14)     NOT NULL,
    [CONTACTNAME] VARCHAR (70)  NOT NULL,
    [PHONE]       VARCHAR (11)  NOT NULL,
    [EMAIL]       VARCHAR (100) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UQ_SUPPLIERS_EMAIL] UNIQUE NONCLUSTERED ([EMAIL] ASC),
    CONSTRAINT [UQ_SUPPLIERS_CNPJ] UNIQUE NONCLUSTERED ([CNPJ] ASC),
    UNIQUE NONCLUSTERED ([CNPJ] ASC)
);
CREATE TABLE [dbo].[SUPPLIERS_PRODUCTS] (
    [SUPPLIERID] INT NOT NULL,
    [PRODUCTID]  INT NOT NULL,
    PRIMARY KEY CLUSTERED ([SUPPLIERID] ASC, [PRODUCTID] ASC),
    CONSTRAINT [FK_SUPPLIERS_PRODUCTS_SUPPLIERS] FOREIGN KEY ([SUPPLIERID]) REFERENCES [dbo].[SUPPLIERS] ([ID]),
    CONSTRAINT [FK_SUPPLIERS_PRODUCTS_PRODUCTS] FOREIGN KEY ([PRODUCTID]) REFERENCES [dbo].[PRODUCTS] ([ID])
);
CREATE TABLE INCOMES
(
ID INT PRIMARY KEY IDENTITY,
SUPPLIERID INT NOT NULL,
CONSTRAINT FK_INCOMES_SUPPLIER FOREIGN KEY (SUPPLIERID)
REFERENCES SUPPLIERS,
ENTRYDATE DATETIME NOT NULL DEFAULT GETDATE(),
EMPLOYEEID INT NOT NULL,
TOTALVALUE FLOAT NOT NULL,
CONSTRAINT FK_INCOMES_EMPLOYEES FOREIGN KEY (EMPLOYEEID)
REFERENCES EMPLOYEES
)

CREATE TABLE INCOMEITEMS
(
INCOMEID INT NOT NULL
CONSTRAINT FK_INCOMEITEMS_INCOMES FOREIGN KEY (INCOMEID)
REFERENCES INCOMES,
PRODUCTID INT NOT NULL
CONSTRAINT FK_INCOMEITEMS_PRODUCTS FOREIGN KEY (PRODUCTID)
REFERENCES PRODUCTS,
QUANTITY INT NOT NULL,
UNITYPRICE FLOAT NOT NULL,
PRIMARY KEY (INCOMEID, PRODUCTID)
)
